<script lang="ts">
  import ImprovedSidebar from "$lib/components/ImprovedSidebar.svelte";
  import FluidLayout from "$lib/components/FluidLayout.svelte";
  import Card from "$lib/components/Card.svelte";
  import Button from "$lib/components/Button.svelte";
  import Input from "$lib/components/Input.svelte";
  import DataTable from "$lib/components/DataTable.svelte";
  import PageHeader from "$lib/components/PageHeader.svelte";
  import LoadingSpinner from "$lib/components/LoadingSpinner.svelte";
  import {
    Package,
    ShoppingBag,
    Plus,
    Edit,
    Trash2,
    Barcode,
    Printer,
    RefreshCw,
    Search,
    X,
    AlertCircle,
    Tag,
    Lock,
    Unlock,
  } from "lucide-svelte";
  import { pb, customFetch } from "$lib/pb";
  import { printBarcode, loadPrintSettings } from "$lib/print";
  import { ProductFormSchema, type Category, firstError } from "$lib/schemas";
  import { onMount } from "svelte";
  import { slide } from "svelte/transition";

  import {
    ArrowLeftRight,
    Store,
    Warehouse,
    TrendingUp,
    Receipt,
  } from "lucide-svelte";

  const menuItems = [
    { label: "Product Management", icon: ShoppingBag, path: "/stock/products" },
    { label: "Stock Management", icon: Package, path: "/stock/inventory" },
    { label: "Warehouse", icon: Warehouse, path: "/stock/warehouse" },
    { label: "Shop Stock", icon: Store, path: "/stock/shops" },
    { label: "Transfers", icon: ArrowLeftRight, path: "/stock/transfers" },
  ];

  interface Product {
    id: string;
    name: string;
    sku: string;
    barcode: string;
    categoryId: string;
    category: string;
    sellingPrice: number;
    costPrice: number;
    taxRate: number;
    details: Record<string, string>;
  }

  let products = $state<Product[]>([]);
  let categories = $state<Category[]>([]);
  let loading = $state(true);
  let errorMsg = $state("");
  let showAddForm = $state(false);
  let editingProduct = $state<Product | null>(null);
  let generatedBarcode = $state("");
  let searchQuery = $state("");
  let searchInputEl = $state<HTMLInputElement | null>(null);
  let saving = $state(false);
  let skuIsAutoGenerated = $state(true);
  let barcodeEditUnlocked = $state(false);
  let barcodeImageUrl = $state<string | null>(null);

  async function loadBarcodeImage(productId: string) {
    try {
      const res = await fetch(`${pb.baseURL}/api/custom/barcode/${productId}`, {
        headers: { Authorization: pb.authStore.token || "" },
      });
      if (!res.ok) return;
      const blob = await res.blob();
      if (barcodeImageUrl) URL.revokeObjectURL(barcodeImageUrl);
      barcodeImageUrl = URL.createObjectURL(blob);
    } catch {
      barcodeImageUrl = null;
    }
  }

  $effect(() => {
    const pid = editingProduct?.id;
    if (pid) {
      loadBarcodeImage(pid);
    } else {
      if (barcodeImageUrl) URL.revokeObjectURL(barcodeImageUrl);
      barcodeImageUrl = null;
    }
  });

  async function generateSku(
    name: string,
    categoryId: string,
  ): Promise<string> {
    if (!name.trim()) return "";
    const cat = categories.find((c) => c.id === categoryId);
    const catPrefix = cat ? cat.name.toUpperCase().slice(0, 3) : "PRD";
    const words = name
      .trim()
      .split(/\s+/)
      .filter((w: string) => w.length >= 2);
    let nameShort: string;
    if (words.length === 0) {
      nameShort = name.trim().toUpperCase().slice(0, 3) || "XXX";
    } else {
      nameShort = words[0].toUpperCase().slice(0, 3);
      if (words.length >= 2) {
        nameShort += "-" + words[1].toUpperCase().slice(0, 2);
      }
    }
    const filter = categoryId ? `category = "${categoryId}"` : `category = ""`;
    const result = await pb.collection("products").getList(1, 1, { filter });
    const counter = String(result.totalItems + 1).padStart(4, "0");
    return `${catPrefix}-${nameShort}-${counter}`;
  }

  $effect(() => {
    const name = formData.name;
    const catId = formData.categoryId;
    if (!showAddForm || editingProduct || !skuIsAutoGenerated) return;
    if (!name.trim()) {
      formData.sku = "";
      return;
    }
    generateSku(name, catId).then((sku) => {
      if (skuIsAutoGenerated) formData.sku = sku;
    });
  });

  let showCategoryForm = $state(false);
  let categoryForm = $state({ name: "", description: "" });
  let savingCategory = $state(false);
  let categoryError = $state("");

  let formData = $state({
    name: "",
    sku: "",
    barcode: "",
    categoryId: "",
    sellingPrice: "",
    costPrice: "",
    taxRate: "0",
    details: [] as { key: string; value: string }[],
  });

  async function loadData() {
    try {
      loading = true;
      const [productRecords, categoryRecords] = await Promise.all([
        pb
          .collection("products")
          .getFullList({ expand: "category", sort: "name" }),
        pb.collection("categories").getFullList({ sort: "name" }),
      ]);
      const cats: Category[] = categoryRecords.map((c: any) => ({
        id: c.id,
        name: c.name,
        description: c.description || "",
      }));
      categories = cats;
      products = productRecords.map((p: any) => ({
        id: p.id,
        name: p.name,
        sku: p.sku || "",
        barcode: p.barcode || "",
        categoryId: p.category || "",
        category: p.expand?.category?.name || "",
        sellingPrice: p.selling_price || 0,
        costPrice: p.cost_price || 0,
        taxRate: p.tax_rate || 0,
        details: p.details || {},
      }));
    } catch (e) {
      errorMsg = "Failed to load products";
    } finally {
      loading = false;
    }
  }

  onMount(() => {
    loadData();
  });

  function resetForm() {
    formData = {
      name: "",
      sku: "",
      barcode: "",
      categoryId: categories[0]?.id || "",
      sellingPrice: "",
      costPrice: "",
      taxRate: "0",
      details: [],
    };
    editingProduct = null;
    showAddForm = false;
    generatedBarcode = "";
    errorMsg = "";
    skuIsAutoGenerated = true;
    barcodeEditUnlocked = false;
  }

  async function handleGenerateBarcodePreview() {
    const result = await pb
      .collection("products")
      .getList(1, 1, { filter: 'barcode != ""', sort: "-barcode" });
    const last = result.items[0]?.barcode;
    const next = last ? parseInt(last, 10) + 1 : 1;
    formData.barcode = String(next).padStart(10, "0");
  }

  async function handleGenerateBarcodeForProduct(product: Product) {
    try {
      const result = await customFetch("/barcode/generate", {
        method: "POST",
        body: JSON.stringify({ product_id: product.id, value: "" }),
      });
      products = products.map((p) =>
        p.id === product.id ? { ...p, barcode: result.barcode } : p,
      );
    } catch (e: any) {
      alert("Failed to generate barcode: " + e.message);
    }
  }

  async function handlePrintBarcode(product: Product) {
    const settings = await loadPrintSettings();
    await printBarcode(
      {
        id: product.id,
        name: product.name,
        selling_price: product.sellingPrice,
        sku: product.sku,
        barcode: product.barcode,
        details: product.details,
      },
      settings,
    );
  }

  async function handleAddCategory(e: SubmitEvent) {
    e.preventDefault();
    savingCategory = true;
    categoryError = "";
    try {
      const record = await pb.collection("categories").create({
        name: categoryForm.name.trim(),
        description: categoryForm.description.trim(),
      });
      categories = [
        ...categories,
        {
          id: record.id,
          name: record["name"],
          description: record["description"] || "",
        },
      ].sort((a, b) => a.name.localeCompare(b.name));
      categoryForm = { name: "", description: "" };
      showCategoryForm = false;
    } catch (e: any) {
      categoryError = e.message || "Failed to add category";
    } finally {
      savingCategory = false;
    }
  }

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    errorMsg = "";
    const parsed = ProductFormSchema.safeParse({
      name: formData.name,
      sku: formData.sku,
      barcode: formData.barcode || undefined,
      categoryId: formData.categoryId,
      sellingPrice: formData.sellingPrice,
      costPrice: formData.costPrice,
      taxRate: formData.taxRate,
    });
    if (!parsed.success) {
      errorMsg = firstError(parsed.error);
      return;
    }
    saving = true;
    try {
      if (!formData.barcode) {
        const result = await pb
          .collection("products")
          .getList(1, 1, { filter: 'barcode != ""', sort: "-barcode" });
        const last = result.items[0]?.barcode;
        const next = last ? parseInt(last, 10) + 1 : 1;
        formData.barcode = String(next).padStart(10, "0");
      }
      const data = {
        name: parsed.data.name,
        sku: parsed.data.sku,
        barcode: formData.barcode,
        category: parsed.data.categoryId,
        selling_price: parsed.data.sellingPrice,
        cost_price: parsed.data.costPrice,
        tax_rate: parsed.data.taxRate,
        details: Object.fromEntries(
          formData.details
            .filter((d) => d.key.trim())
            .map((d) => [d.key.trim(), d.value]),
        ),
      };
      if (editingProduct) {
        await pb.collection("products").update(editingProduct.id, data);
      } else {
        await pb.collection("products").create(data);
      }
      await loadData();
      resetForm();
    } catch (e: any) {
      errorMsg = e.message || "Failed to save product";
    } finally {
      saving = false;
    }
  }

  function handleEdit(product: Product) {
    editingProduct = product;
    skuIsAutoGenerated = false;
    formData = {
      name: product.name,
      sku: product.sku,
      barcode: product.barcode,
      categoryId: product.categoryId,
      sellingPrice: String(product.sellingPrice),
      costPrice: String(product.costPrice),
      taxRate: String(product.taxRate),
      details: Object.entries(product.details || {}).map(([key, value]) => ({
        key,
        value: String(value),
      })),
    };
    generatedBarcode = product.barcode;
    showAddForm = true;
  }

  async function handleDelete(id: string) {
    if (!confirm("Are you sure you want to delete this product?")) return;
    try {
      await pb.collection("products").delete(id);
      products = products.filter((p) => p.id !== id);
    } catch (e: any) {
      alert("Failed to delete: " + e.message);
    }
  }

  function handleWindowKeydown(e: KeyboardEvent) {
    const target = e.target as HTMLElement;
    const isInputFocused =
      target.tagName === "INPUT" ||
      target.tagName === "TEXTAREA" ||
      target.tagName === "SELECT";
    if (
      !isInputFocused &&
      e.key.length === 1 &&
      !e.ctrlKey &&
      !e.metaKey &&
      !e.altKey &&
      !loading &&
      searchInputEl
    ) {
      e.preventDefault();
      searchQuery += e.key;
      searchInputEl.focus();
    }
  }

  let filteredProducts = $derived(
    (() => {
      const q = searchQuery.trim().toLowerCase();
      if (!q) return products;
      return products.filter(
        (p) =>
          p.name.toLowerCase().includes(q) ||
          p.category.toLowerCase().includes(q) ||
          p.barcode.toLowerCase().includes(q) ||
          p.sku.toLowerCase().includes(q),
      );
    })(),
  );

  const columns: any[] = [
    { header: "SKU", accessor: "sku" },
    { header: "Product Name", accessor: "name" },
    { header: "Category", accessor: "category" },
    { header: "Selling Price", accessor: "sellingPrice" },
    { header: "Cost Price", accessor: "costPrice" },
    { header: "Tax", accessor: "taxRate" },
    { header: "Actions" },
  ];
</script>

<svelte:window onkeydown={handleWindowKeydown} />

<svelte:head>
  <title>Product Management - My Garments</title>
</svelte:head>

<div class="flex min-h-screen bg-background">
  <ImprovedSidebar {menuItems} userRole="Stock Manager" />

  {#snippet actionButton()}
    <Button
      icon={showAddForm ? X : Plus}
      onclick={() => {
        if (showAddForm) {
          showAddForm = false;
        } else {
          resetForm();
          showAddForm = true;
        }
      }}
    >
      {showAddForm ? "Cancel" : "Add Product"}
    </Button>
  {/snippet}

  <FluidLayout>
    <PageHeader
      title="Product Management"
      subtitle="Manage product catalog and barcodes"
      icon={ShoppingBag}
      action={actionButton}
    />

    {#if errorMsg}
      <div
        class="mb-4 flex items-center gap-2 p-3 bg-destructive/10 border border-destructive/30 rounded-lg text-destructive text-sm"
      >
        <AlertCircle class="w-4 h-4" />
        {errorMsg}
      </div>
    {/if}

    <!-- Add/Edit Form -->
    {#if showAddForm}
      <div transition:slide={{ duration: 300 }}>
        <Card class="mb-6 md:mb-8">
          <h3 class="mb-6 text-lg md:text-xl">
            {editingProduct ? "Edit Product" : "Add New Product"}
          </h3>
          <form onsubmit={handleSubmit} class="space-y-6">
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
              <Input label="Product Name" bind:value={formData.name} required />
              <Input
                label="SKU"
                bind:value={formData.sku}
                required
                onchange={() => {
                  skuIsAutoGenerated = false;
                }}
              />

              <div class="relative w-full mb-6">
                <label
                  class="block mb-2 text-sm text-muted-foreground"
                  for="cat"
                  >Category <span class="text-destructive">*</span></label
                >
                <select
                  id="cat"
                  bind:value={formData.categoryId}
                  class="w-full px-4 py-3 bg-input-background border border-border rounded-lg outline-none focus:ring-2 focus:ring-ring transition-all"
                  required
                >
                  <option value="">Select category</option>
                  {#each categories as cat}
                    <option value={cat.id}>{cat.name}</option>
                  {/each}
                </select>
              </div>

              <Input
                label="Selling Price (₹)"
                type="number"
                bind:value={formData.sellingPrice}
                required
              />
              <Input
                label="Cost Price (₹)"
                type="number"
                bind:value={formData.costPrice}
                required
              />
              <Input
                label="Tax Rate (%)"
                type="number"
                bind:value={formData.taxRate}
              />
            </div>

            <!-- Product Details (key-value pairs) -->
            <div class="space-y-3">
              <div class="flex items-center justify-between">
                <h4 class="text-sm font-medium">Product Details</h4>
                <button
                  type="button"
                  onclick={() =>
                    (formData.details = [
                      ...formData.details,
                      { key: "", value: "" },
                    ])}
                  class="flex items-center gap-1 px-3 py-1.5 text-sm bg-muted hover:bg-muted/80 rounded-lg transition-colors"
                >
                  <Plus class="w-3.5 h-3.5" /> Add Row
                </button>
              </div>
              {#if formData.details.length === 0}
                <p class="text-sm text-muted-foreground italic">
                  No details yet. Add key-value pairs for attributes like Color,
                  Size, Material…
                </p>
              {:else}
                <div class="space-y-2">
                  {#each formData.details as detail, i}
                    <div class="flex gap-2 items-center">
                      <Input
                        placeholder="Key (e.g. Color)"
                        bind:value={detail.key}
                      />
                      <Input
                        placeholder="Value (e.g. Red)"
                        bind:value={detail.value}
                      />
                      <button
                        type="button"
                        onclick={() =>
                          (formData.details = formData.details.filter(
                            (_, j) => j !== i,
                          ))}
                        class="p-2 hover:bg-muted rounded transition-colors shrink-0"
                        title="Remove row"
                      >
                        <X class="w-4 h-4 text-muted-foreground" />
                      </button>
                    </div>
                  {/each}
                </div>
              {/if}
            </div>

            <!-- Barcode Section -->
            <Card class="bg-muted/50">
              <h4 class="mb-4 flex items-center gap-2">
                <Barcode class="w-5 h-5 text-primary" />
                Barcode Management
              </h4>
              <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                <div class="relative">
                  <Input
                    label="Barcode Number"
                    bind:value={formData.barcode}
                    disabled={!!formData.barcode && !barcodeEditUnlocked}
                  />
                  {#if formData.barcode}
                    <button
                      type="button"
                      onclick={() => (barcodeEditUnlocked = !barcodeEditUnlocked)}
                      class="absolute right-3 top-4 text-muted-foreground hover:text-foreground transition-colors"
                      title={barcodeEditUnlocked ? "Lock barcode" : "Unlock to edit"}
                    >
                      {#if barcodeEditUnlocked}
                        <Unlock class="w-4 h-4 text-primary" />
                      {:else}
                        <Lock class="w-4 h-4" />
                      {/if}
                    </button>
                  {/if}
                </div>
                <div class="flex items-end gap-2">
                  {#if !formData.barcode}
                    <Button
                      type="button"
                      variant="outline"
                      icon={RefreshCw}
                      onclick={handleGenerateBarcodePreview}
                      class="flex-1">Auto Generate</Button
                    >
                  {/if}
                  <Button
                    type="button"
                    variant="secondary"
                    icon={Printer}
                    onclick={() =>
                      handlePrintBarcode({
                        id: editingProduct?.id ?? "",
                        name: formData.name,
                        sku: formData.sku,
                        barcode: formData.barcode,
                        sellingPrice: Number(formData.sellingPrice),
                        costPrice: Number(formData.costPrice),
                        taxRate: Number(formData.taxRate),
                        categoryId: formData.categoryId,
                        category: "",
                        details: Object.fromEntries(
                          formData.details
                            .filter((d) => d.key.trim())
                            .map((d) => [d.key.trim(), d.value]),
                        ),
                      } as Product)}
                    disabled={!formData.barcode}>Print</Button
                  >
                </div>
              </div>
              {#if formData.barcode}
                <div
                  transition:slide={{ duration: 200 }}
                  class="p-4 bg-white border-2 border-primary rounded-lg text-center"
                >
                  <p class="text-xs text-muted-foreground mb-2">
                    Barcode Preview
                  </p>
                  <div class="flex flex-col items-center justify-center gap-2">
                    {#if barcodeImageUrl}
                      <img src={barcodeImageUrl} alt="Barcode" class="h-20" />
                    {:else}
                      <Barcode class="w-20 h-20 text-primary" />
                    {/if}
                    <p class="font-mono text-xl tracking-wider">
                      {formData.barcode}
                    </p>
                    <p class="text-sm text-muted-foreground">
                      {formData.name || "Product Name"}
                    </p>
                  </div>
                </div>
              {/if}
            </Card>

            <div class="flex gap-3">
              <Button type="submit" disabled={saving}
                >{saving
                  ? "Saving…"
                  : editingProduct
                    ? "Update Product"
                    : "Add Product"}</Button
              >
              <Button type="button" variant="outline" onclick={resetForm}
                >Cancel</Button
              >
            </div>
          </form>
        </Card>
      </div>
    {/if}

    <!-- Category Management Section -->
    <Card class="mb-6 md:mb-8">
      <div class="flex items-center justify-between mb-4">
        <h3 class="text-lg md:text-xl flex items-center gap-2">
          <Tag class="w-5 h-5 text-primary" />
          Categories ({categories.length})
        </h3>
        <button
          onclick={() => {
            showCategoryForm = !showCategoryForm;
            categoryError = "";
            categoryForm = { name: "", description: "" };
          }}
          class="flex items-center gap-1.5 px-3 py-2 text-sm bg-primary text-primary-foreground rounded-lg hover:opacity-90 transition-opacity"
        >
          {#if showCategoryForm}
            <X class="w-4 h-4" /> Cancel
          {:else}
            <Plus class="w-4 h-4" /> Add Category
          {/if}
        </button>
      </div>

      {#if showCategoryForm}
        <div transition:slide={{ duration: 250 }} class="mb-4 overflow-hidden">
          <form
            onsubmit={handleAddCategory}
            class="p-4 bg-muted rounded-lg space-y-3"
          >
            {#if categoryError}
              <div
                class="flex items-center gap-2 text-sm text-destructive bg-destructive/10 border border-destructive/20 rounded-lg px-3 py-2"
              >
                <AlertCircle class="w-4 h-4 shrink-0" />
                {categoryError}
              </div>
            {/if}
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div>
                <label
                  class="block text-sm text-muted-foreground mb-1"
                  for="catName"
                >
                  Category Name <span class="text-destructive">*</span>
                </label>
                <input
                  id="catName"
                  type="text"
                  bind:value={categoryForm.name}
                  placeholder="e.g. Saree, Shirt, Kurta…"
                  required
                  class="w-full px-3 py-2 bg-background border border-border rounded-lg outline-none focus:ring-2 focus:ring-ring text-sm transition-all"
                />
              </div>
              <div>
                <label
                  class="block text-sm text-muted-foreground mb-1"
                  for="catDesc">Description</label
                >
                <input
                  id="catDesc"
                  type="text"
                  bind:value={categoryForm.description}
                  placeholder="Optional description"
                  class="w-full px-3 py-2 bg-background border border-border rounded-lg outline-none focus:ring-2 focus:ring-ring text-sm transition-all"
                />
              </div>
            </div>
            <div class="flex gap-2">
              <button
                type="submit"
                disabled={savingCategory}
                class="px-4 py-2 text-sm bg-primary text-primary-foreground rounded-lg hover:opacity-90 disabled:opacity-50 transition-opacity"
              >
                {savingCategory ? "Saving…" : "Save Category"}
              </button>
              <button
                type="button"
                onclick={() => (showCategoryForm = false)}
                class="px-4 py-2 text-sm border border-border rounded-lg hover:bg-muted transition-colors"
              >
                Cancel
              </button>
            </div>
          </form>
        </div>
      {/if}

      {#if categories.length === 0}
        <p class="text-sm text-muted-foreground py-4 text-center">
          No categories yet. Add one above.
        </p>
      {:else}
        <div class="flex flex-wrap gap-2">
          {#each categories as cat (cat.id)}
            <span
              class="px-3 py-1.5 bg-primary/10 text-primary rounded-full text-sm font-medium"
              title={cat.description || undefined}
            >
              {cat.name}
            </span>
          {/each}
        </div>
      {/if}
    </Card>

    <!-- Products Table -->
    <Card>
      <div
        class="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-5"
      >
        <h3 class="text-lg md:text-xl">
          All Products
          <span class="ml-2 text-sm font-normal text-muted-foreground">
            ({filteredProducts.length}{searchQuery
              ? ` of ${products.length}`
              : ""})
          </span>
        </h3>
        <div class="relative w-full sm:w-72">
          <Search
            class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground pointer-events-none"
          />
          <input
            type="text"
            bind:value={searchQuery}
            bind:this={searchInputEl}
            placeholder="Search by name, SKU or category…"
            class="w-full pl-9 pr-9 py-2 text-sm border border-border rounded-full bg-muted/40 outline-none focus:ring-2 focus:ring-ring transition-all"
          />
          {#if searchQuery}
            <button
              onclick={() => (searchQuery = "")}
              class="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground transition-colors"
            >
              <X class="w-3.5 h-3.5" />
            </button>
          {/if}
        </div>
      </div>

      {#if loading}
        <LoadingSpinner />
      {:else if filteredProducts.length === 0}
        <div class="text-center py-12 text-muted-foreground">
          <Search class="w-10 h-10 mx-auto mb-3 opacity-30" />
          <p class="text-sm">
            {searchQuery
              ? `No products match "${searchQuery}"`
              : "No products yet. Add your first product above."}
          </p>
        </div>
      {:else}
        {#snippet cell(row: any, column: any)}
          {#if column.header === "SKU"}
            <div class="flex items-center gap-2">
              <Barcode class="w-4 h-4 text-primary shrink-0" />
              <span class="font-mono text-sm">{row.sku}</span>
            </div>
          {:else if column.header === "Category"}
            <span class="px-2 py-1 bg-primary/10 text-primary rounded text-sm"
              >{row.category}</span
            >
          {:else if column.header === "Selling Price"}
            <span>₹{row.sellingPrice.toLocaleString()}</span>
          {:else if column.header === "Cost Price"}
            <span>₹{row.costPrice.toLocaleString()}</span>
          {:else if column.header === "Tax"}
            <span>{row.taxRate}%</span>
          {:else if column.header === "Actions"}
            <div class="flex gap-2">
              <button
                onclick={() => handleEdit(row)}
                class="p-2 hover:bg-muted rounded transition-colors"
                title="Edit"
              >
                <Edit class="w-4 h-4 text-primary" />
              </button>
              <button
                onclick={() => handleGenerateBarcodeForProduct(row)}
                class="p-2 hover:bg-muted rounded transition-colors"
                title="Generate Barcode from Server"
              >
                <RefreshCw class="w-4 h-4 text-secondary" />
              </button>
              <button
                onclick={() => handlePrintBarcode(row)}
                class="p-2 hover:bg-muted rounded transition-colors"
                title="Print Barcode"
              >
                <Printer class="w-4 h-4 text-secondary" />
              </button>
              <button
                onclick={() => handleDelete(row.id)}
                class="p-2 hover:bg-muted rounded transition-colors"
                title="Delete"
              >
                <Trash2 class="w-4 h-4 text-destructive" />
              </button>
            </div>
          {:else}
            {row[column.accessor]}
          {/if}
        {/snippet}

        <DataTable data={filteredProducts} {columns} {cell} />
      {/if}
    </Card>
  </FluidLayout>
</div>
